dist: jammy # focal
# see all versions at https://hub.docker.com/_/ubuntu
sudo: false
language: python
python:
  #- "3.6"   # dataclasses came in 3.7, so 3.6 isnt supported
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - sudo apt-get -y update
  - python3 setup.py install

install:
  - pip install pytest-cov
  - pip install .

script:
  - python3 -m pytest
